package com.solarisbank.frauddetection.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Structured response returned by the fraud evaluation endpoint.
 *
 * The {@code aiExplanation} field is only populated when the fraud score
 * meets or exceeds the configured reject threshold (default: 0.65), triggering
 * the Amazon Bedrock RAG explanation pipeline. It is omitted from the JSON
 * response entirely when null.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@JsonInclude(JsonInclude.Include.NON_NULL)
public class EvaluationResponse {

    /**
     * Fraud probability score produced by the ONNX model.
     * Range: 0.0 (no risk) to 1.0 (certain fraud).
     * Returns -1.0 if inference failed (tensor shape mismatch or model error).
     */
    private double score;

    /**
     * Final system decision based on configured thresholds.
     * <ul>
     *   <li>APPROVED  — score &lt; 0.40</li>
     *   <li>REVIEW    — 0.40 &le; score &lt; 0.65</li>
     *   <li>REJECTED  — score &ge; 0.65</li>
     * </ul>
     */
    private String decision;

    /**
     * Natural-language explanation generated by the Amazon Bedrock Fraud Analyst Copilot.
     * Only present when decision is REJECTED.
     * Omitted from JSON response when null.
     */
    private String aiExplanation;
}
